# Generated by Django 4.1.1 on 2022-09-11 03:58

from django.db import migrations, models
import djongo.models.fields
import gestor_cursos.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id_curso', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('codigo_asignatura', models.CharField(max_length=30)),
                ('grupo', models.SmallIntegerField()),
                ('horarios', djongo.models.fields.ArrayField(model_container=gestor_cursos.models.Horario)),
                ('cupos_disponibles', models.SmallIntegerField()),
                ('cupos_totales', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CursoInscrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_curso', models.CharField(max_length=30)),
                ('documento_estudiante', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('documento_identidad', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=100)),
                ('email_institucional', models.EmailField(max_length=254)),
            ],
        ),
    ]
