# Generated by Django 4.1.1 on 2022-09-11 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_cursos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CursoInscrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_curso', models.CharField(max_length=30)),
                ('documento_estudiante', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='curso',
            name='id_curso',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
